# Chargement et formatage des donnees et echantillonage

## Chargement

In [114]:
import pandas as pd

In [115]:
df = pd.read_csv("full_2020.csv")
df

C:\Users\Augusta\AppData\Local\Temp\ipykernel_35028\1185203041.py:1: DtypeWarning: Columns (8,10,12,14,16,17,18,20,22,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("full_2020.csv")

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2020-1,2020-01-07,1,Vente,8000.0,NaN,NaN,FORTUNAT,B063,1250.0,...,NaN,NaN,NaN,T,terres,NaN,NaN,1061.0,5.323540,46.171919
1,2020-2,2020-01-02,1,Vente,2175.0,NaN,NaN,TERRES DES CINQ SAULES,B124,1290.0,...,NaN,NaN,NaN,BT,taillis simples,NaN,NaN,85.0,4.893436,46.251868
2,2020-2,2020-01-02,1,Vente,2175.0,NaN,NaN,BOIS DU CHAMP RION,B006,1290.0,...,NaN,NaN,NaN,T,terres,NaN,NaN,1115.0,4.899919,46.235327
3,2020-2,2020-01-02,1,Vente,2175.0,NaN,NaN,EN COROBERT,B025,1290.0,...,NaN,NaN,NaN,T,terres,NaN,NaN,1940.0,4.882347,46.246519
4,2020-2,2020-01-02,1,Vente,2175.0,NaN,NaN,TERRES DES CINQ SAULES,B124,1290.0,...,NaN,NaN,NaN,T,terres,NaN,NaN,1148.0,4.894688,46.251820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2459555,2020-1075291,2020-12-16,1,Vente,1937500.0,24.0,NaN,RUE CHANOINESSE,1748,75004.0,...,Appartement,87.0,4.0,S,sols,NaN,NaN,447.0,2.350481,48.854293
2459556,2020-1075291,2020-12-16,1,Vente,1937500.0,24.0,NaN,RUE CHANOINESSE,1748,75004.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,447.0,2.350481,48.854293
2459557,2020-1075291,2020-12-16,1,Vente,1937500.0,24.0,NaN,RUE CHANOINESSE,1748,75004.0,...,Appartement,82.0,2.0,S,sols,NaN,NaN,447.0,2.350481,48.854293
2459558,2020-1075291,2020-12-16,1,Vente,1937500.0,24.0,NaN,RUE CHANOINESSE,1748,75004.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,447.0,2.350481,48.854293
2459559,2020-1075292,2020-10-08,1,Adjudication,255000.0,39.0,NaN,RUE SAINT-SAUVEUR,8752,75002.0,...,Appartement,21.0,1.0,NaN,NaN,NaN,NaN,NaN,2.348149,48.865935

## Echantillonage

In [116]:
df_sampled_2020 = df.sample(frac = 0.3)

In [117]:
df_sampled_2020

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
1868480,2020-791356,2020-11-06,1,Vente,174800.0,6.0,NaN,RUE LOUIS JOUVET,0388,78390.0,...,Appartement,38.0,2.0,NaN,NaN,NaN,NaN,NaN,2.013482,48.805325
110669,2020-48776,2020-06-04,1,Vente,150000.0,NaN,NaN,MOULIN NEUF,B075,6440.0,...,NaN,NaN,NaN,AG,terrains d'agrément,NaN,NaN,134.0,7.381663,43.797849
966419,2020-402976,2020-07-21,1,Vente,157500.0,NaN,NaN,PIERRE JACQUES,B060,42800.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,281.0,4.613997,45.538646
283565,2020-124402,2020-09-11,1,Vente,426275.0,5012.0,NaN,LE PT VAUVILLE,B114,14800.0,...,Maison,180.0,5.0,S,sols,NaN,NaN,1124.0,0.056109,49.321337
1201947,2020-499010,2020-03-11,1,Vente,143000.0,50.0,NaN,RUE DES JUIFS,0700,50400.0,...,Appartement,48.0,3.0,NaN,NaN,NaN,NaN,NaN,-1.600013,48.837937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270386,2020-118579,2020-08-28,1,Vente,732000.0,15.0,NaN,CHE DES BASTIDES,0510,13960.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,647.0,5.116398,43.332524
273348,2020-119982,2020-05-12,1,Vente,6500.0,NaN,NaN,BOIS NOEL,B002,13103.0,...,NaN,NaN,NaN,P,prés,MARAI,Pré marais,7250.0,4.724679,43.803090
1744181,2020-734401,2020-11-09,1,Vente,430726.3,6.0,NaN,RUE PAUL BERT,0970,74100.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,389.0,6.237120,46.193677
1766441,2020-744493,2020-10-29,1,Vente,155000.0,132.0,NaN,RUE DU RENARD,6900,76000.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1.077310,49.449849
1430945,2020-598813,2020-04-30,1,Vente,115000.0,87.0,NaN,RUE PUISSANT,0460,59460.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,76.0,4.100183,50.300895

In [118]:
df_sampled_2020.dtypes

id_mutation                      object
date_mutation                    object
numero_disposition                int64
nature_mutation                  object
valeur_fonciere                 float64
adresse_numero                  float64
adresse_suffixe                  object
adresse_nom_voie                 object
adresse_code_voie                object
code_postal                     float64
code_commune                     object
nom_commune                      object
code_departement                 object
ancien_code_commune             float64
ancien_nom_commune               object
id_parcelle                      object
ancien_id_parcelle               object
numero_volume                    object
lot1_numero                      object
lot1_surface_carrez             float64
lot2_numero                      object
lot2_surface_carrez             float64
lot3_numero                      object
lot3_surface_carrez             float64
lot4_numero                     float64
lot4_surface_carrez             float64
lot5_numero                     float64
lot5_surface_carrez             float64
nombre_lots                       int64
code_type_local                 float64
type_local                       object
surface_reelle_bati             float64
nombre_pieces_principales       float64
code_nature_culture              object
nature_culture                   object
code_nature_culture_speciale     object
nature_culture_speciale          object
surface_terrain                 float64
longitude                       float64
latitude                        float64
dtype: object

## Nettoyage

In [121]:
# supression des collonnes a donees manquanes a plus de 90 %
df_sampled_2020= df_sampled_2020[df_sampled_2020.columns[df_sampled_2020.isna().sum()/df_sampled_2020.shape[0]<0.75]]

In [123]:
df_sampled_2020.columns

Index(['id_mutation', 'date_mutation', 'numero_disposition', 'nature_mutation',
       'valeur_fonciere', 'adresse_numero', 'adresse_nom_voie',
       'adresse_code_voie', 'code_postal', 'code_commune', 'nom_commune',
       'code_departement', 'id_parcelle', 'lot1_numero', 'nombre_lots',
       'code_type_local', 'type_local', 'surface_reelle_bati',
       'nombre_pieces_principales', 'code_nature_culture', 'nature_culture',
       'surface_terrain', 'longitude', 'latitude'],
      dtype='object')

In [124]:
df_sampled_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 737868 entries, 1868480 to 1430945
Data columns (total 24 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   id_mutation                737868 non-null  object
 1   date_mutation              737868 non-null  object
 2   numero_disposition         737868 non-null  int64
 3   nature_mutation            737868 non-null  object
 4   valeur_fonciere            728442 non-null  float64
 5   adresse_numero             441133 non-null  float64
 6   adresse_nom_voie           728554 non-null  object
 7   adresse_code_voie          728607 non-null  object
 8   code_postal                728595 non-null  float64
 9   code_commune               737868 non-null  object
 10  nom_commune                737868 non-null  object
 11  code_departement           737868 non-null  object
 12  id_parcelle                737868 non-null  object
 13  lot1_numero                227456 non-null  object
 14  nombre_lots                737868 non-null  int64
 15  code_type_local            394812 non-null  float64
 16  type_local                 394812 non-null  object
 17  surface_reelle_bati        303511 non-null  float64
 18  nombre_pieces_principales  394345 non-null  float64
 19  code_nature_culture        507197 non-null  object
 20  nature_culture             507197 non-null  object
 21  surface_terrain            507177 non-null  float64
 22  longitude                  729004 non-null  float64
 23  latitude                   729004 non-null  float64
dtypes: float64(9), int64(2), object(13)
memory usage: 140.7+ MB

In [125]:
# nettoyage des donnees manquantes
# pour ne pas pedre des odnnes j'affecte les valkeurs moyennes aux donnees manquantes dans 
#valeur foncieres, surface terrain et nomvre de pieces manquantes

df_sampled_2020['valeur_fonciere'] = df_sampled_2020['valeur_fonciere'].fillna(value=df['valeur_fonciere'].mean())
df_sampled_2020['surface_terrain'] = df_sampled_2020['surface_terrain'].fillna(value=df['surface_terrain'].mean())
df_sampled_2020['nombre_pieces_principales'] = df_sampled_2020['nombre_pieces_principales'].fillna(value=df['nombre_pieces_principales'].mean())



# suppression des lignes vides
for i in df_sampled_2020.columns:
    if (df_sampled_2020.isnull().values.any() == True):
        df_sampled_2020.dropna(axis = 0, inplace=True)

C:\Users\Augusta\AppData\Local\Temp\ipykernel_35028\2406106477.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sampled_2020['valeur_fonciere'] = df_sampled_2020['valeur_fonciere'].fillna(value=df['valeur_fonciere'].mean())
C:\Users\Augusta\AppData\Local\Temp\ipykernel_35028\2406106477.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sampled_2020['surface_terrain'] = df_sampled_2020['surface_terrain'].fillna(value=df['surface_terrain'].mean())
C:\Users\Augusta\AppData\Local\Temp\ipykernel_35028\2406106477.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sampled_2020['nombre_pieces_principales'] = df_sampled_2020['nombre_pieces_principales'].fillna(value=df['nombre_pieces_principales'].mean())
C:\Users\Augusta\AppData\Local\Temp\ipykernel_35028\2406106477.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sampled_2020.dropna(axis = 0, inplace=True)

In [126]:
df_sampled_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 590 entries, 2285323 to 1639939
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_mutation                590 non-null    object
 1   date_mutation              590 non-null    object
 2   numero_disposition         590 non-null    int64
 3   nature_mutation            590 non-null    object
 4   valeur_fonciere            590 non-null    float64
 5   adresse_numero             590 non-null    float64
 6   adresse_nom_voie           590 non-null    object
 7   adresse_code_voie          590 non-null    object
 8   code_postal                590 non-null    float64
 9   code_commune               590 non-null    object
 10  nom_commune                590 non-null    object
 11  code_departement           590 non-null    object
 12  id_parcelle                590 non-null    object
 13  lot1_numero                590 non-null    object
 14  nombre_lots                590 non-null    int64
 15  code_type_local            590 non-null    float64
 16  type_local                 590 non-null    object
 17  surface_reelle_bati        590 non-null    float64
 18  nombre_pieces_principales  590 non-null    float64
 19  code_nature_culture        590 non-null    object
 20  nature_culture             590 non-null    object
 21  surface_terrain            590 non-null    float64
 22  longitude                  590 non-null    float64
 23  latitude                   590 non-null    float64
dtypes: float64(9), int64(2), object(13)
memory usage: 115.2+ KB

## Quelques test de fonctions

In [56]:
df_sampled_2020.to_csv("df_sampled_2020.csv")

In [132]:
 df_sampled_2020['nombre_pieces_principales'].unique()

array([3., 0., 4., 5., 6., 2., 1., 7., 8., 9.])

In [133]:
 df_sampled_2020['nombre_pieces_principales'].max()

9.0

In [134]:
df_sampled_2020["code_departement"].unique()

array([93, 78, 59, 72, 37, 38, 28, 33, 91, 64, 83, 69, 77, 40, 94, 44, 4,
       5, 34, 13, 60, 14, 45, 76, 11, 6, 85, 50, 84, 74, 63, 53, 54, 7,
       61, 30, 73, 1, 26, 95, 56, 35, 27, 49, 70, 80, 18, 10, 22, 71, 42,
       '30', 46, 9, 89, 31, 87, 41, 92, 58], dtype=object)

In [108]:

def get_regions (code_departement):
    auvergne = ['01','03','07','15','26','38','42','43','63','69','73','74']
    bourgogne = ['21','25','39','58','70','71','89','90']
    bretagne = ['22','29','35','56']
    val_loire = ['18','28','36','37','41','45']
    corse = ['20']
    ile_de_france = ['75','77','78','91','92','93','94','95']
    est = ['08','10','51','52','54','55','57','67','68','88']
    haut_france = ['02','59','60','62','80']
    normandie = ['14','27','50','61','76']
    aquitaine = ['16','17','19','23','24','33','40','47','64','79','86','87']
    occitanie = ['09','11','12','30','31','32','34','46','48','65','66','81','82']
    pays_loire = ['44','49','53','72','85']
    provence = ['04','05','06','13','83','84']
    

    region =''

    if (code_departement in auvergne):
        region = "AUVERGNE-RHÔNE-ALPES"

    elif (code_departement in bourgogne):
        region = "BOURGOGNE-FRANCHE-COMTÉ"
    
    elif (code_departement in bretagne):
        region = "BRETAGNE"
    
    elif (code_departement in val_loire):
        region = "CENTRE-VAL-DE-LOIRE"
    
    elif (code_departement in corse):
        region = "CORSE"

    elif (code_departement in ile_de_france):
        region = "ÎLE-DE-FRANCE"

    elif (code_departement in est):
        region = "GRAND-EST"

    elif (code_departement in haut_france):
        region = "HAUT-DE-FRANCE"

    elif (code_departement in normandie):
        region = "NORMANDIE"

    elif (code_departement in aquitaine):
        region = "NOUVELLE-AQUITAINE"

    elif (code_departement in occitanie):
        region = "OCCITANIE"

    elif (code_departement in pays_loire):
        region = "PAYS-DE-LA-LOIRE"

    elif (code_departement in provence):
        region = "PROVENCE-ALPES-CÔTE D'AZUR"
    
    else:
        region = "CORSE"

    return region